In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import StandardScaler

In [15]:
df = pd.read_csv('data/ems_weather.csv')

### **Model 1: Kitchen Sink**

In [17]:
# Alrighttttttt purpose of Model 1 is to get a general baseline to which we can compare our scores.
# Will also run a Model 1.5 with scaling after I run the initial fit and score.
df.dropna(inplace = True)

X = df.drop(columns = 'TAVG_CALC')
y = df['TAVG_CALC']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [18]:
linreg = LinearRegression()

linreg.fit(X_train, y_train)

print(f'Training: {linreg.score(X_train, y_train)}')
print(f'Testing: {linreg.score(X_test, y_test)}')

Training: 1.0
Testing: 1.0


In [22]:
linreg.coef_

array([-1.03523292e-15, -1.28331713e-15, -1.18231935e-12, -1.05505778e-11,
       -5.20429186e-13, -3.47930018e-12,  3.38812312e-13, -4.35484981e-14,
       -7.51315676e-13,  2.45793837e-13, -2.18136273e-13,  4.68375339e-17,
       -4.19732261e-11,  1.68540246e-10,  2.32130213e-11,  2.19293988e-11,
       -2.56681807e-11, -6.77741049e-11,  6.67055387e-17, -7.58316099e-12,
       -4.19497517e-11, -1.02940693e-10, -5.41016884e-17, -4.90637429e-11,
       -1.58801737e-16, -4.72243356e-11, -3.54735437e-12, -9.05696555e-11,
       -1.12961003e-10, -2.07667624e-10, -3.11486847e-10, -1.14176022e-10,
       -9.89223694e-11, -3.14065676e-11, -8.21952044e-11, -1.96626331e-10,
       -5.72210030e-11, -4.32845101e-11, -4.50418538e-11, -4.70866203e-11,
       -8.41072533e-11,  1.40296646e-11,  1.55515176e-11, -6.27125617e-11,
       -1.23815888e-16, -7.37639821e-11, -1.93883702e-10,  2.24693213e-11,
       -3.29840695e-10, -4.75076107e-11, -1.11462656e-10,  1.38714485e-11,
       -1.82828480e-10, -

This does not seem likely, not sure yet why this is the result but there is definitely something not quite right here.

In [20]:
lasso = Ridgeso()

lasso.fit(X_train, y_train)

print(f'Training: {lasso.score(X_train, y_train)}')
print(f'Testing: {lasso.score(X_test, y_test)}')

Training: 0.9999861745257597
Testing: 0.9999863759344229


C:\Users\tacia\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 14363.686290611606, tolerance: 420.91716732946657
  model = cd_fast.enet_coordinate_descent(


In [21]:
lasso.coef_

array([ 2.07254913e-07, -1.01865888e-08,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.24777394e-08,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  

In [23]:
ridge = Ridge()

ridge.fit(X_train, y_train)

print(f'Training: {lasso.score(X_train, y_train)}')
print(f'Testing: {lasso.score(X_test, y_test)}')

Training: 0.9999861745257597
Testing: 0.9999863759344229


C:\Users\tacia\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=8.88102e-22): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,


In [24]:
ridge.coef_

array([-7.09507021e-12,  1.25536982e-11, -8.09927613e-08,  1.90851390e-07,
       -7.57802073e-10,  0.00000000e+00, -8.83723170e-10,  2.67956195e-09,
        0.00000000e+00, -7.52536490e-10,  1.15193135e-09,  1.94076051e-12,
        1.11935599e-07,  3.24807889e-07,  0.00000000e+00,  1.76488806e-07,
        2.75997629e-07, -6.84088092e-08,  0.00000000e+00,  1.14336279e-07,
       -1.70039261e-06,  1.37465962e-07,  0.00000000e+00, -8.79668974e-07,
        0.00000000e+00, -5.32456812e-07,  1.58475206e-06,  1.17857027e-06,
        5.89575939e-07, -1.08049929e-06,  2.60996751e-06,  7.78611146e-07,
        1.30834717e-07,  1.19882550e-06,  1.25492446e-07, -2.56271554e-06,
       -1.84260955e-06,  6.75613536e-08, -1.00928853e-06,  4.83664042e-07,
        2.54820323e-07,  2.03594277e-06,  3.05799652e-06, -3.91564489e-07,
        0.00000000e+00,  1.05013540e-07,  8.63530607e-07, -1.15731155e-06,
       -7.80555813e-07,  1.79524756e-06,  1.39671369e-06, -1.00721927e-06,
        1.68072720e-06,  